export const ACTION_TYPES = {
  REQUEST_LOGIN: "REQUEST_LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT: "LOGOUT",
  LOGIN_ERROR: "LOGIN_ERROR",
  REQUEST_REGISTER: "REQUEST_REGISTER",
  REQUEST_REGISTER: "REQUEST_REGISTER",
};
