FROM public.ecr.aws/lambda/nodejs:14
ENV NODE_ENV=production
WORKDIR /var/task
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
RUN npm install --production --silent
COPY . .
EXPOSE 3001
ENTRYPOINT ["npm", "start"]